name: Basic pull request checks

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr-title-check:
    runs-on: self-hosted
    outputs:
      run_id: ${{ steps.run_id.outputs.run_id }}
    steps:
      - uses: SatelCreative/pr-title-gitmoji-check@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false

      # To  make sure next job only runs one 1st commit
      - name: Get run id
        id: run_id
        if: ${{ github.event_name == 'pull_request' &&  github.event.action == 'opened'}}
        run: echo "run_id=1" >> $GITHUB_OUTPUT    

  broken-link-check:
    needs: pr-title-check
    if: ${{ needs.pr-title-check.outputs.run_id == 1 }}
    runs-on: ubuntu-latest #switch to self hosted after the network issue at the office is fixed
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7
  
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
